Chapter 07
# 使用NumPy计算矩阵乘法
Book_1《编程不难》 | 鸢尾花书：从加减乘除到机器学习 

In [1]:
import numpy as np

# 定义矩阵 A 和 B
A = np.array([[1, 2, 10, 20],
              [3, 4, 30, 40]])
        
B = np.array([[1, 3],
              [2, 4],
              [10, 30],
              [20, 40]])

In [2]:
C = A @ B; print(C)

[[ 505 1111]
 [1111 2525]]


In [3]:
D = B @ A; print(D)

[[  10   14  100  140]
 [  14   20  140  200]
 [ 100  140 1000 1400]
 [ 140  200 1400 2000]]
